### ISSUE TITLE
PythonAppDelegate not found

### ISSUE THREAD

**Issue by jerincodekyt** [dimaqq/pios#2]
Downloaded `Python-3.5-iOS-support.b5.tar.gz`  since `Python-3.6-iOS-support.b1.tar.gz` was throwing bitcode error. 
Now as per doc ran `pip3 install -t app_packages https://github.com/pybee/rubicon-objc/archive/master.zip --upgrade`
This installed the `rubicon_objc-0.2.10-py3.6.egg-info` and related libraries.
But once I deploy the project I am getting `PythonAppDelegate` missing error.
Following is the xcode log.

`2018-01-23 12:01:22.002125+0530 Dishuhu Malala Arkuyaya[4059:1865402] DEBUG:root:bootstrap logging initialised`
`2018-01-23 12:01:22.006282+0530 Dishuhu Malala Arkuyaya[4059:1865402] ERROR:root:something went wrong
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/F57CE6DC-D52A-40E7-BA42-B0981D5A810A/Dishuhu Malala Arkuyaya.app/Library/Application Support/com.example.dimark/app/dimark/app.py", line 22, in <module>
    runpy.run_module("ui")
  File "/var/containers/Bundle/Application/F57CE6DC-D52A-40E7-BA42-B0981D5A810A/Dishuhu Malala Arkuyaya.app/Library/Python.framework/Resources/lib/python35.zip/runpy.py", line 201, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/var/containers/Bundle/Application/F57CE6DC-D52A-40E7-BA42-B0981D5A810A/Dishuhu Malala Arkuyaya.app/Library/Python.framework/Resources/lib/python35.zip/runpy.py", line 136, in _get_module_details
    raise error("No module named %s" % mod_name)
ImportError: No module named ui`

`2018-01-23 12:01:22.006525+0530 Dishuhu Malala Arkuyaya[4059:1865402] Python code loaded, trying to get entry point`
`2018-01-23 12:01:22.040907+0530 Dishuhu Malala Arkuyaya[4059:1865402] *** Assertion failure in void _UIApplicationMainPreparations(int, char **, NSString *__strong, NSString *__strong)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3698.33.7/UIApplication.m:3915`

`2018-01-23 12:01:22.041254+0530 Dishuhu Malala Arkuyaya[4059:1865402] Python runtime error: Unable to instantiate the UIApplication delegate instance. No class named PythonAppDelegate is loaded.`
`2018-01-23 12:01:22.058503+0530 Dishuhu Malala Arkuyaya[4059:1865402] Leaving`

**Comment by dimaqq** [comment]
Let me see what's up with newest 3.6 deps.
It's possible that 3.6 is incidentally required, I have to test that.

The real error here is `ImportError: No module named ui`

Which is supposed to be provided by `app_packages/ui/__main__.py`

**Comment by jerincodekyt** [comment]
@dimaqq thank you for prompt reply.
As I am new to iOS dev, how can I go about fixing the `ImportError`. Since its already showing up in project with `__init__.py` being an empty file.

**Comment by dimaqq** [comment]
Empty `__init__.py` is pretty common in Python, it marks this directory as module or submodule.

What happens is that either file is not available (didn't get bundled somehow, or is looked up at a wrong path), or possibly there was an error loading `__main__.py`, e.g. if one of the import's inside that file failed or some symbol lookup at global scope failed.

Since low-level logging apparently works (it's set up in `app/dimark/app.py`), feel free to sprinkle logging statements trying to figure this out.

**Comment by jerincodekyt** [comment]
So I moved all files and folders under `app_packages` into `app` and it successfully ran on simulator. 
But while running it on iPhone its trying to run `ui -> __init__.py` instead of `__main__.py` (sprinkling some logging statements inside init file proved that). 
As per your comment in code `def __init__(self): init is not ran, as this is instantiated by ObjC runtime`.
Any idea why it doesn't run __main__.py directly? Is it because rubicon is not being executed?

**Comment by dimaqq** [comment]
Hi @jerincodekyt I just re-run fresh checkout from the repo, following the steps in README.md.

Following configuration worked for me :)

* `dimaqq/pios` (trunk)
* `pybee/rubicon-objc/archive/master.zip` (trunk)
* `dimaqq/Python-Apple-support` `Python-3.6-iOS-support.b1.tar.gz`
* XCode `Version 9.2 (9C40b)`

I suggest you should focus on why 3.6b1 binary deps didn't work for you.

Note the content of `pybee/Python-Apple-support` releases has changed, the tarball used to be ~49MB and now the releases are <400KB. I don't know what's up with that. Likewise I can't recall if 3.5b1 worked and if there were any limitations.
